const ActionTypes = {
  INITIALIZE:      'INITIALIZE',
  ON_PORT_UPDATE:  'ON_PORT_UPDATE',
  SORT_GROUPS:     'SORT_GROUPS',
  SORT_PORTS:      'SORT_PORTS',
  ON_SELECT_GROUP: 'ON_SELECT_GROUP',
  CLOSE_PORTS:     'CLOSE_PORTS',
  ON_WS_MESSAGE:   'ON_WS_MESSAGE',
};

export default ActionTypes;
